backend:
  name: github
  repo: xjensen/news   # Path to your Github/Gitlab repository
  branch: master    # Branch to update
  base_url: https://canews-oauth-functions.azurewebsites.net # Path to ext auth provider
  auth_endpoint: /api/auth
media_folder: "src/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads
local_backend: true

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Layout" 
        name: "layout"
        widget: "hidden"
        default: "index.html"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Body"
        name: "body"
        widget: "markdown"

      - label: "Summary"
        name: "meta"
        widget: "text"

      - label: "Preview Image"
        name: "previewimage"
        widget: "image"
        default: "/img/prev-hello-ca.jpg"
        media_library:
          config:
            multiple: false

      - label: "Lead"
        name: "lead"
        widget: "string"

      - label: "Author"
        name: "author"
        widget: "string"
        default: "JP Petrucione"

      - label: "Publish Date"
        name: "publishdate"
        widget: "datetime"
        format: "MM/DD/YYYY"
        date_format: "MM/DD/YYYY" 
        time_format: "HH:mm"

      - label: "Tag List"
        name: "tags"
        widget: "list"
        default: ["news"]

